language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
sudo: false
before_script:
  - mix deps.get
<<<<<<< HEAD
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
=======
script:
  - mix test
>>>>>>> develop
